# Generated by Django 5.0.6 on 2024-06-13 11:12

import django.db.models.deletion
import new_account.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('pin', models.IntegerField(max_length=4)),
                ('account_number', models.IntegerField(default=new_account.utility.generate_account_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Account_Type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('DOMICILIARY', 'Domiciliary')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('TRANSFER', 'Transfer')], default='CREDIT', max_length=10)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField()),
                ('Transaction_status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='SUCCESSFUL', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_account.account')),
            ],
        ),
    ]
