# Generated by Django 5.0.6 on 2024-07-02 09:02

import new_account.utility
import new_account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(default=new_account.utility.generate_account_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('pin', models.CharField(max_length=4, validators=[new_account.validators.validate_pin])),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('DOMICILIARY', 'Domiciliary')], default='SAVINGS', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('TRANSFER', 'Transfer')], default='CREDIT', max_length=10)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('Transaction_status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='SUCCESSFUL', max_length=10)),
            ],
        ),
    ]
