# Generated by Django 5.0.6 on 2024-06-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_account', '0002_rename_balance_account_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_balance',
            new_name='balance',
        ),
    ]
